---

- name: Run bdcom command
  hosts: bdcom
  gather_facts: false
  connection: local
  tasks:

    - name: run commands
      ansible.netcommon.telnet:
        user: yuorlogin
        password: yourpassw
        login_prompt: 'Username: '
        prompts:
        - '[>#]'
        command:
          - enable
          - config
          - terminal length 0
          - epon onu-config-template {{item}}
          - no cmd-sequence 4
          - cmd-sequence 4 epon sla upstream pir 1000000 cir 1000
          - cmd-sequence 5 epon sla downstream pir 1000000 cir 1000
          - cmd-sequence 6 exit
          - exit
          - write all
          - show running-config non-interface
      with_items:
        - T1
        - T2
        - T3
        - T4
        - T5
        - T6
        - T7
        - T8
      register: output
      
    - name: output
      debug:
        msg: "{{ output.results|map(attribute='output')|first}}"
