---
- name: Backup Mikrotik
  gather_facts: false
  hosts: all
  vars:
    backup_dir: "/var/lib/awx/projects/Backups"
    awx_username: '{{ lookup("env", "ANSIBLE_NET_USERNAME") }}'
    awx_password: '{{ lookup("env", "ANSIBLE_NET_PASSWORD") }}'
  tasks:
    - name: Export
      ansible.builtin.shell: >-
        sshpass -p {{awx_password}} ssh -o StrictHostKeyChecking=no {{awx_username}}@{{ inventory_hostname }} /export
      register: export
      delegate_to: localhost

    - name: Backup
      ansible.builtin.copy:
        content: "{{ export.stdout }}"
        dest: "{{ backup_dir }}/{{ inventory_hostname }}_config.{{ lookup('pipe', 'date +%Y-%m-%d@%H:%M:%S') }}"
      when: export is defined
      delegate_to: localhost
