---
- name: cisco Nexus3000 C3064PQ
  hosts: all
  gather_facts: false
  connection: network_cli

  vars:
    backup_dir: "/var/lib/awx/projects/Backups"
    awx_username: '{{ lookup("env", "ANSIBLE_NET_USERNAME") }}'
    awx_password: '{{ lookup("env", "ANSIBLE_NET_PASSWORD") }}'

    cli:
      host: "{{ inventory_hostname }}"
      username: {{ awx_username }}
      password: {{ awx_password }}
      authorize: true

  tasks:
    - name: run show running-config on remote devices
      ios_command:
        commands: "show running-config"
        provider: "{{ cli }}"
      register: config

    - name: Backup
      ansible.builtin.copy:
        content: "{{ config.stdout }}"
        dest: "{{ backup_dir }}/{{ inventory_hostname }}_config.{{ lookup('pipe', 'date +%Y-%m-%d@%H:%M:%S') }}"
      when: export is defined
      delegate_to: localhost
