---

- name: Run bdcom backup
  hosts: bdcom_olts
  gather_facts: false
  connection: local
  vars:
    backup_dir: "/root/ANS/backup/GoldenBackUps/network/olts"

  tasks:

    - name: run show commands
      ios_command:
        commands:
          - enable
          - terminal length 0
          - show running-config
      register: show_result

    - name: Debug registered var
      debug: var=show_result.stdout_lines

    - name: Backup
      ansible.builtin.copy:
        content: "{{ show_result.stdout|join('\n') }}"
        dest: "{{ backup_dir }}/{{ inventory_hostname }}_config.{{ lookup('pipe', 'date +%Y-%m') }}"
      when: show_result is defined
      delegate_to: localhost

